# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Calc-Gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 477)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(350, 477))
        MainWindow.setMaximumSize(QtCore.QSize(350, 477))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.SevenBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SevenBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.SevenBtn.setFont(font)
        self.SevenBtn.setObjectName("SevenBtn")
        self.gridLayout.addWidget(self.SevenBtn, 3, 0, 1, 1)
        self.EightBtn = QtWidgets.QPushButton(self.centralwidget)
        self.EightBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.EightBtn.setFont(font)
        self.EightBtn.setObjectName("EightBtn")
        self.gridLayout.addWidget(self.EightBtn, 3, 1, 1, 1)
        self.ZeroBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ZeroBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ZeroBtn.setFont(font)
        self.ZeroBtn.setFlat(False)
        self.ZeroBtn.setObjectName("ZeroBtn")
        self.gridLayout.addWidget(self.ZeroBtn, 6, 0, 1, 1)
        self.MulBtn = QtWidgets.QPushButton(self.centralwidget)
        self.MulBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.MulBtn.setFont(font)
        self.MulBtn.setObjectName("MulBtn")
        self.gridLayout.addWidget(self.MulBtn, 4, 3, 1, 1)
        self.DotBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DotBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.DotBtn.setFont(font)
        self.DotBtn.setObjectName("DotBtn")
        self.gridLayout.addWidget(self.DotBtn, 6, 1, 1, 1)
        self.EulerBtn = QtWidgets.QPushButton(self.centralwidget)
        self.EulerBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.EulerBtn.setFont(font)
        self.EulerBtn.setObjectName("EulerBtn")
        self.gridLayout.addWidget(self.EulerBtn, 2, 0, 1, 1)
        self.TwoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.TwoBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.TwoBtn.setFont(font)
        self.TwoBtn.setObjectName("TwoBtn")
        self.gridLayout.addWidget(self.TwoBtn, 5, 1, 1, 1)
        self.EqualsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.EqualsBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.EqualsBtn.setFont(font)
        self.EqualsBtn.setIconSize(QtCore.QSize(30, 30))
        self.EqualsBtn.setObjectName("EqualsBtn")
        self.gridLayout.addWidget(self.EqualsBtn, 6, 3, 1, 1)
        self.CBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CBtn.setMinimumSize(QtCore.QSize(80, 50))
        self.CBtn.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.CBtn.setFont(font)
        self.CBtn.setObjectName("CBtn")
        self.gridLayout.addWidget(self.CBtn, 0, 3, 1, 1)
        self.RootBtn = QtWidgets.QPushButton(self.centralwidget)
        self.RootBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RootBtn.setFont(font)
        self.RootBtn.setObjectName("RootBtn")
        self.gridLayout.addWidget(self.RootBtn, 0, 1, 1, 1)
        self.NineBtn = QtWidgets.QPushButton(self.centralwidget)
        self.NineBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.NineBtn.setFont(font)
        self.NineBtn.setObjectName("NineBtn")
        self.gridLayout.addWidget(self.NineBtn, 3, 2, 1, 1)
        self.OneBtn = QtWidgets.QPushButton(self.centralwidget)
        self.OneBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.OneBtn.setFont(font)
        self.OneBtn.setObjectName("OneBtn")
        self.gridLayout.addWidget(self.OneBtn, 5, 0, 1, 1)
        self.FourBtn = QtWidgets.QPushButton(self.centralwidget)
        self.FourBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FourBtn.setFont(font)
        self.FourBtn.setObjectName("FourBtn")
        self.gridLayout.addWidget(self.FourBtn, 4, 0, 1, 1)
        self.FiveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.FiveBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FiveBtn.setFont(font)
        self.FiveBtn.setObjectName("FiveBtn")
        self.gridLayout.addWidget(self.FiveBtn, 4, 1, 1, 1)
        self.ThreeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ThreeBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ThreeBtn.setFont(font)
        self.ThreeBtn.setObjectName("ThreeBtn")
        self.gridLayout.addWidget(self.ThreeBtn, 5, 2, 1, 1)
        self.DivBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DivBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.DivBtn.setFont(font)
        self.DivBtn.setObjectName("DivBtn")
        self.gridLayout.addWidget(self.DivBtn, 5, 3, 1, 1)
        self.PowBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PowBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PowBtn.setFont(font)
        self.PowBtn.setObjectName("PowBtn")
        self.gridLayout.addWidget(self.PowBtn, 0, 0, 1, 1)
        self.RdnBtn = QtWidgets.QPushButton(self.centralwidget)
        self.RdnBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RdnBtn.setFont(font)
        self.RdnBtn.setObjectName("RdnBtn")
        self.gridLayout.addWidget(self.RdnBtn, 2, 2, 1, 1)
        self.SubBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SubBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.SubBtn.setFont(font)
        self.SubBtn.setObjectName("SubBtn")
        self.gridLayout.addWidget(self.SubBtn, 3, 3, 1, 1)
        self.LogBtn = QtWidgets.QPushButton(self.centralwidget)
        self.LogBtn.setMinimumSize(QtCore.QSize(80, 50))
        self.LogBtn.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LogBtn.setFont(font)
        self.LogBtn.setObjectName("LogBtn")
        self.gridLayout.addWidget(self.LogBtn, 0, 2, 1, 1)
        self.AddBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AddBtn.setMinimumSize(QtCore.QSize(80, 50))
        self.AddBtn.setMaximumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.AddBtn.setFont(font)
        self.AddBtn.setObjectName("AddBtn")
        self.gridLayout.addWidget(self.AddBtn, 2, 3, 1, 1)
        self.AnsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AnsBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.AnsBtn.setFont(font)
        self.AnsBtn.setObjectName("AnsBtn")
        self.gridLayout.addWidget(self.AnsBtn, 6, 2, 1, 1)
        self.SixBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SixBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.SixBtn.setFont(font)
        self.SixBtn.setObjectName("SixBtn")
        self.gridLayout.addWidget(self.SixBtn, 4, 2, 1, 1)
        self.PiBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PiBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PiBtn.setFont(font)
        self.PiBtn.setObjectName("PiBtn")
        self.gridLayout.addWidget(self.PiBtn, 2, 1, 1, 1)
        self.PercBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PercBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PercBtn.setFont(font)
        self.PercBtn.setObjectName("PercBtn")
        self.gridLayout.addWidget(self.PercBtn, 1, 0, 1, 1)
        self.PromBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PromBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PromBtn.setFont(font)
        self.PromBtn.setObjectName("PromBtn")
        self.gridLayout.addWidget(self.PromBtn, 1, 1, 1, 1)
        self.FactBtn = QtWidgets.QPushButton(self.centralwidget)
        self.FactBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FactBtn.setFont(font)
        self.FactBtn.setObjectName("FactBtn")
        self.gridLayout.addWidget(self.FactBtn, 1, 2, 1, 1)
        self.AbsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AbsBtn.setMinimumSize(QtCore.QSize(80, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.AbsBtn.setFont(font)
        self.AbsBtn.setObjectName("AbsBtn")
        self.gridLayout.addWidget(self.AbsBtn, 1, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.Input = QtWidgets.QLineEdit(self.centralwidget)
        self.Input.setMinimumSize(QtCore.QSize(330, 80))
        self.Input.setMaximumSize(QtCore.QSize(330, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Input.setFont(font)
        self.Input.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.Input.setFrame(True)
        self.Input.setClearButtonEnabled(True)
        self.Input.setObjectName("Input")
        self.gridLayout_2.addWidget(self.Input, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuN_pov_da = QtWidgets.QMenu(self.menuBar)
        self.menuN_pov_da.setObjectName("menuN_pov_da")
        MainWindow.setMenuBar(self.menuBar)
        self.menuBar.addAction(self.menuN_pov_da.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Input, self.PowBtn)
        MainWindow.setTabOrder(self.PowBtn, self.RootBtn)
        MainWindow.setTabOrder(self.RootBtn, self.LogBtn)
        MainWindow.setTabOrder(self.LogBtn, self.CBtn)
        MainWindow.setTabOrder(self.CBtn, self.PercBtn)
        MainWindow.setTabOrder(self.PercBtn, self.PromBtn)
        MainWindow.setTabOrder(self.PromBtn, self.FactBtn)
        MainWindow.setTabOrder(self.FactBtn, self.AbsBtn)
        MainWindow.setTabOrder(self.AbsBtn, self.EulerBtn)
        MainWindow.setTabOrder(self.EulerBtn, self.PiBtn)
        MainWindow.setTabOrder(self.PiBtn, self.RdnBtn)
        MainWindow.setTabOrder(self.RdnBtn, self.AddBtn)
        MainWindow.setTabOrder(self.AddBtn, self.SevenBtn)
        MainWindow.setTabOrder(self.SevenBtn, self.EightBtn)
        MainWindow.setTabOrder(self.EightBtn, self.NineBtn)
        MainWindow.setTabOrder(self.NineBtn, self.SubBtn)
        MainWindow.setTabOrder(self.SubBtn, self.FourBtn)
        MainWindow.setTabOrder(self.FourBtn, self.FiveBtn)
        MainWindow.setTabOrder(self.FiveBtn, self.SixBtn)
        MainWindow.setTabOrder(self.SixBtn, self.MulBtn)
        MainWindow.setTabOrder(self.MulBtn, self.OneBtn)
        MainWindow.setTabOrder(self.OneBtn, self.TwoBtn)
        MainWindow.setTabOrder(self.TwoBtn, self.ThreeBtn)
        MainWindow.setTabOrder(self.ThreeBtn, self.DivBtn)
        MainWindow.setTabOrder(self.DivBtn, self.ZeroBtn)
        MainWindow.setTabOrder(self.ZeroBtn, self.DotBtn)
        MainWindow.setTabOrder(self.DotBtn, self.AnsBtn)
        MainWindow.setTabOrder(self.AnsBtn, self.EqualsBtn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Deus Vult Calculator"))
        self.SevenBtn.setText(_translate("MainWindow", "7"))
        self.EightBtn.setText(_translate("MainWindow", "8"))
        self.ZeroBtn.setText(_translate("MainWindow", "0"))
        self.MulBtn.setText(_translate("MainWindow", "×"))
        self.DotBtn.setText(_translate("MainWindow", "."))
        self.EulerBtn.setText(_translate("MainWindow", "e"))
        self.TwoBtn.setText(_translate("MainWindow", "2"))
        self.EqualsBtn.setText(_translate("MainWindow", "="))
        self.CBtn.setText(_translate("MainWindow", "C"))
        self.RootBtn.setText(_translate("MainWindow", "√x"))
        self.NineBtn.setText(_translate("MainWindow", "9"))
        self.OneBtn.setText(_translate("MainWindow", "1"))
        self.FourBtn.setText(_translate("MainWindow", "4"))
        self.FiveBtn.setText(_translate("MainWindow", "5"))
        self.ThreeBtn.setText(_translate("MainWindow", "3"))
        self.DivBtn.setText(_translate("MainWindow", "÷"))
        self.PowBtn.setText(_translate("MainWindow", "x^n"))
        self.RdnBtn.setText(_translate("MainWindow", "Rnd"))
        self.SubBtn.setText(_translate("MainWindow", "-"))
        self.LogBtn.setText(_translate("MainWindow", "log"))
        self.AddBtn.setText(_translate("MainWindow", "+"))
        self.AnsBtn.setText(_translate("MainWindow", "Ans"))
        self.SixBtn.setText(_translate("MainWindow", "6"))
        self.PiBtn.setText(_translate("MainWindow", "π"))
        self.PercBtn.setText(_translate("MainWindow", "%"))
        self.PromBtn.setText(_translate("MainWindow", "‰"))
        self.FactBtn.setText(_translate("MainWindow", "x!"))
        self.AbsBtn.setText(_translate("MainWindow", "abs"))
        self.menuN_pov_da.setTitle(_translate("MainWindow", "Nápověda"))


